# Generated by Django 4.2 on 2025-08-14 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
